# Generated by Django 3.0.5 on 2020-09-09 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 16, 46, 8, 622809), editable=False),
        ),
    ]
