# Generated by Django 3.0.5 on 2020-09-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0005_gallery_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
